name: Manual Release to Docker Hub

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARENAXR_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ARENAXR_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: graph-monitoring    

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            chash=${{ github.sha }}
            version=${{ steps.get_release.outputs.tag_name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/arena-broker, ${{ secrets.DOCKER_HUB_USERNAME }}/arena-broker:${{ steps.get_release.outputs.tag_name }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
